#! /usr/bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:


                                               
ssh -o StrictHostKeyChecking=accept-new ha1.tsand.org sudo gluster \
	volume create vol_disk \
	replica 3 \
	arbiter 1 \
	10.0.0.121:/glusterstorage/vol_dist \
	10.0.0.122:/glusterstorage/vol_dist \
	10.0.0.123:/glusterstorage/vol_dist 
